mkdir -p pretrained/network_g

echo Downloading LED_Pretrain_None_None_MM22_Setting_Ratio100-300.pth...
python scripts/download_gdrive.py --id 1FSXp_vJxbo8_dbMJPiA33DZfagn1ExHA --save-path pretrained/network_g/LED_Pretrain_None_None_MM22_Setting_Ratio100-300.pth

echo Downloading LED_Pretrain_None_None_CVPR20_Setting_Ratio100-300.pth...
python scripts/download_gdrive.py --id 1kIN_eyNd4mlKhPV4PMmgzaoE3ddagjNU --save-path pretrained/network_g/LED_Pretrain_None_None_CVPR20_Setting_Ratio100-300.pth

echo Downloading LED_Pretrain_None_None_CVPR20_Setting_Ratio1-200.pth...
python scripts/download_gdrive.py --id 1IzOkJuHWQVXmkzFJzQ9-gkPXBlrutO2p --save-path pretrained/network_g/LED_Pretrain_None_None_CVPR20_Setting_Ratio1-200.pth

echo Downloading LED_Deploy_SID_SonyA7S2_MM22_Setting_Ratio100-300.pth...
python scripts/download_gdrive.py --id 1OocWgk6hENF3XwEDU3pah-3-NVGx_xJF --save-path pretrained/network_g/LED_Deploy_SID_SonyA7S2_MM22_Setting_Ratio100-300.pth

echo Downloading LED_Deploy_SID_SonyA7S2_CVPR20_Setting_Ratio100-300.pth...
python scripts/download_gdrive.py --id 1vmeJBdXSjecnbTXLrMHOIhLgJbMFRaA1 --save-path pretrained/network_g/LED_Deploy_SID_SonyA7S2_CVPR20_Setting_Ratio100-300.pth

echo Downloading LED_Deploy_ELD_SonyA7S2_CVPR20_Setting_Ratio1-200.pth...
python scripts/download_gdrive.py --id 1jpcMKqC59iVLmTMI8lCLQxd3wwg0dr76 --save-path pretrained/network_g/LED_Deploy_ELD_SonyA7S2_CVPR20_Setting_Ratio1-200.pth

echo Downloading LED_Deploy_ELD_NikonD850_CVPR20_Setting_Ratio1-200.pth...
python scripts/download_gdrive.py --id 1OScdkp6vXLe4sF__pMJhwnIqhnUCMcFo --save-path pretrained/network_g/LED_Deploy_ELD_NikonD850_CVPR20_Setting_Ratio1-200.pth

echo Downloading ELD_Deploy_SID_SonyA7S2_MM22_Setting_Ratio100-300.pth...
python scripts/download_gdrive.py --id 1F4pNlro1egoACSgcXOLaARXx6ko35Gvi --save-path pretrained/network_g/ELD_Deploy_SID_SonyA7S2_MM22_Setting_Ratio100-300.pth

echo Downloading ELD_Deploy_ELD_SonyA7S2_CVPR20_Setting_Ratio1-200.pth...
python scripts/download_gdrive.py --id 1o0kr446Se2j5iemXiLjHxXy5UjLqgc6c --save-path pretrained/network_g/ELD_Deploy_ELD_SonyA7S2_CVPR20_Setting_Ratio1-200.pth

echo Downloading ELD_Deploy_ELD_NikonD850_CVPR20_Setting_Ratio1-200.pth...
python scripts/download_gdrive.py --id 1seTloGkpM2XbeeSwKSJHvq9khICnbfLv --save-path pretrained/network_g/ELD_Deploy_ELD_NikonD850_CVPR20_Setting_Ratio1-200.pth

echo Downloading PG_Deploy_SID_SonyA7S2_CVPR20_Setting_Ratio100-300.pth...
python scripts/download_gdrive.py --id 1aNVsic0BRWPESUk6yU-OFcLYgCtdZkOj --save-path pretrained/network_g/PG_Deploy_SID_SonyA7S2_CVPR20_Setting_Ratio100-300.pth

echo Downloading PG_Deploy_ELD_SonyA7S2_CVPR20_Setting_Ratio1-200.pth...
python scripts/download_gdrive.py --id 1B-92vP5RzK1xv8nLVnrIOb2IBbjHGJRU --save-path pretrained/network_g/PG_Deploy_ELD_SonyA7S2_CVPR20_Setting_Ratio1-200.pth

echo Downloading PG_Deploy_ELD_NikonD850_CVPR20_Setting_Ratio1-200.pth...
python scripts/download_gdrive.py --id 1m7l2EsaoZQoM-9ot2kFiTEQdDs5vYwi- --save-path pretrained/network_g/PG_Deploy_ELD_NikonD850_CVPR20_Setting_Ratio1-200.pth

echo Downloading SID_Deploy_SID_SonyA7S2_CVPR20_Setting_Ratio100-300.pth...
python scripts/download_gdrive.py --id 1Rz5oShriEBFYQLiIXL8uKVhkWFsZuY9P --save-path pretrained/network_g/SID_Deploy_SID_SonyA7S2_CVPR20_Setting_Ratio100-300.pth
